
plugins:
  -
    - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: docs
          release: patch
        # - type: style
        #   release: patch
        - type: refactor
          release: patch
        - type: perf
          release: patch
        # - type: test
        #   release: patch
        # - type: chore
        #   release: patch
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  -
    - '@semantic-release/git'
    - assets:
        - package.json
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  -
    - '@semantic-release/github'
    - assets:
        - dist/savagedom.js
