language: node_js

node_js:
- 8

env:
  DEPLOY_BUILD=false

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          condition: $DEPLOY_BUILD = true

deploy:
  provider: pages
  local_dir: docs
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master

notifications:
  email: false

sudo: false
