language: node_js

node_js:
- 6
- 8

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

notifications:
  email: false

sudo: false

cache:
  directories:
  - node_modules
